apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: flask-app
  files: 
  - src/app.py
- name: flask-index
  files: 
  - src/templates/index.html
  - src/templates/register.html
  - src/templates/comp-of-registration.html
  - src/templates/confirm.html
  - src/templates/input.html
  - src/templates/novel_detail.html
- name: nginx-conf
  files:
  - src/nginx.conf
- name: my-conf
  files:
  - src/my.cnf
resources:
- ./yaml/flask.yaml
- ./yaml/mysql_pv.yaml
- ./yaml/mysql.yaml
- ./yaml/nginx-deployment.yaml
- ./yaml/nginx-service.yaml
