---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-hoge
  labels:
    app: phpmyadmin-hoge
  namespace: novel-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-hoge
  template:
    metadata:
      labels:
        app: phpmyadmin-hoge
    spec:
      containers:
        - name: phpmyadmin-hoge
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-hoge
            - name: PMA_PORT
              value: '3306'
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service-hoge
  namespace: novel-back-end
spec:
  type: NodePort
  selector:
    app: phpmyadmin-hoge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


