apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-hoge
  name: flask-hoge
spec:
  type: ClusterIP
  selector:
    app: flask-hoge
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hoge
  labels:
    app: flask-hoge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hoge
  template:
    metadata:
      labels:
        app: flask-hoge
    spec:
      containers:
        - image: python:3.9.17-slim-bullseye
          name: flask-hoge
          tty: true
          command:
            - sh
            - -c
            - |
              apt update \
              && apt upgrade -y \
              && apt install -y curl \
              && echo 'install nvim' \
              && curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage \
              && chmod u+x nvim.appimage \
              && ./nvim.appimage --appimage-extract \
              && ./squashfs-root/AppRun --version \
              && ln -s /squashfs-root/AppRun /usr/bin/nvim \
              && echo 'complete install nvim' \
              && useradd -mU flask -s /bin/bash \
              && echo 'flask ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
              && cd /home/flask/ \
              && python3 -m venv .venv \
              && . .venv/bin/activate \
              && echo "active venv!" \
              && pip install --upgrade pip \
              && pip install Flask mysql-connector-python \
              && echo "complete pip install" \
              && cp /usr/src/app.py /home/flask/app.py \
              && mkdir -p /home/flask/templates \
              && cp /usr/src/index.html /home/flask/templates/index.html \
              && ls \
              && echo $FLASK_APP \
              && flask run --host=0.0.0.0
          ports:
            - containerPort: 8080
              name: flask-hoge
          volumeMounts:
            - name: flask-data
              mountPath: /home/flask
            - name: flask-app
              mountPath: /usr/src/
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: flask-data
          emptyDir: {}
        - name: flask-app
          projected:
            sources:
              - configMap:
                  name: flask-app
              - configMap:
                  name: flask-index
---
