---
apiVersion: v1
kind: Service
metadata:
  name: mysql-hoge
  labels:
    app: mysql-hoge
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-hoge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-hoge
  labels:
    app: mysql-hoge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-hoge
  template:
    metadata:
      labels:
        app: mysql-hoge
    spec:
      containers:
        - image: mysql:8.0.33-oracle
          name: mysql-hoge
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: flask_db
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: pass
          ports:
            - containerPort: 3306
              name: mysql-hoge
          volumeMounts:
            - name: mysql-local-storage-hoge
              mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: mysql-local-storage-hoge
          persistentVolumeClaim:
            claimName: mysql-pvc-hoge

