apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app-proxy
    name: nginx-proxy
  name: nginx-proxy-service
spec:
  selector:
    app: nginx-app-proxy
    name: nginx-proxy
  type: NodePort
  ports:
  - port: 31333
    nodePort: 30515
    protocol: TCP
    targetPort: nginx-port
