apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-app-proxy
    name: nginx-proxy
  name: nginx-default-conf
data:
  default.conf: |-
    error_log /var/log/nginx/error.log;
    server {
      listen      80;
      listen  [::]:80;
      server_name localhost;
      error_page  500 502 503 504 /50x.html;
      location = /50x.html {
        root  /usr/share/nginx/html;
      }
      proxy_set_header  Host  $host;
      proxy_set_header  X-Real-IP  $remote_addr;
      proxy_set_header  X-Forwarded-Host    $host;
      proxy_set_header  X-Forwarded-Server  $host;
      proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
      location / {
        proxy_pass http://flask-hoge.c0118050.svc.cluster.local:5000/;
        # 基本はキャッシュしない
        set $do_not_cache 1;
        # 画像のみキャッシュさせる
        if ($uri ~* "\.(jpg|jpeg|png|gif|css|js|ico|webm)$") {
                 set $do_not_cache 0;
        }
        proxy_no_cache $do_not_cache;

        # キャッシュの検索
        proxy_cache_bypass $do_not_cache;
        # バックエンド no-cache を無視
        proxy_ignore_headers Cache-Control;
        # キャッシュのキーゾーンを指定
        proxy_cache cache_key;
        # キャッシュの有効時間を指定
        proxy_cache_valid 200 302 60m;
        proxy_cache_valid 404 10m;
        # キャッシュのステータスヘッダーを追加
        add_header X-Cache-Status $upstream_cache_status;
      }
    }
